stages:
  - deploy

pages:
  image: instrumentisto/flutter:latest
  stage: deploy

  script:
    - cd my_assignment
    - flutter pub get
    - flutter build web
    - cd ..
    - mkdir public
    - cp -r my_assignment/build/web/* public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == "assignment2"
  environment: production

