// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgsiQprycj-UmDiFQ8doXViJ5Dj9P1kjs',
    appId: '1:75851733463:ios:2065f4bbea7ca07261d392',
    messagingSenderId: '75851733463',
    projectId: 'csci567-f25-e5b42',
    storageBucket: 'csci567-f25-e5b42.firebasestorage.app',
    iosBundleId: 'com.example.myAssignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDM5AMXqA9G7E51tqk_RD0V5NDrxufUWho',
    appId: '1:75851733463:web:c4ce8c458288d5c861d392',
    messagingSenderId: '75851733463',
    projectId: 'csci567-f25-e5b42',
    authDomain: 'csci567-f25-e5b42.firebaseapp.com',
    storageBucket: 'csci567-f25-e5b42.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDM5AMXqA9G7E51tqk_RD0V5NDrxufUWho',
    appId: '1:75851733463:web:c4ce8c458288d5c861d392',
    messagingSenderId: '75851733463',
    projectId: 'csci567-f25-e5b42',
    authDomain: 'csci567-f25-e5b42.firebaseapp.com',
    storageBucket: 'csci567-f25-e5b42.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgsiQprycj-UmDiFQ8doXViJ5Dj9P1kjs',
    appId: '1:75851733463:ios:2065f4bbea7ca07261d392',
    messagingSenderId: '75851733463',
    projectId: 'csci567-f25-e5b42',
    storageBucket: 'csci567-f25-e5b42.firebasestorage.app',
    iosBundleId: 'com.example.myAssignment',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcS0GLNJZTIZPEpgcvlYod-VKqv7zZXlc',
    appId: '1:75851733463:android:49657a848dbbae8661d392',
    messagingSenderId: '75851733463',
    projectId: 'csci567-f25-e5b42',
    storageBucket: 'csci567-f25-e5b42.firebasestorage.app',
  );

}