// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQnrOugDRlh71XjYgrjChthfjCDYZ0M2o',
    appId: '1:606862688252:web:715c69d50d8c46637bfc79',
    messagingSenderId: '606862688252',
    projectId: 'ourobre-project',
    authDomain: 'ourobre-project.firebaseapp.com',
    storageBucket: 'ourobre-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDc8sLbaknSp7aTmwlmobw72P0KsQOj15w',
    appId: '1:606862688252:android:14bb84e70eb1c5177bfc79',
    messagingSenderId: '606862688252',
    projectId: 'ourobre-project',
    storageBucket: 'ourobre-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATuObnpW7UmJQgxcgsliH-DxHJThrHgzU',
    appId: '1:606862688252:ios:82e72b542c4680ef7bfc79',
    messagingSenderId: '606862688252',
    projectId: 'ourobre-project',
    storageBucket: 'ourobre-project.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATuObnpW7UmJQgxcgsliH-DxHJThrHgzU',
    appId: '1:606862688252:ios:82e72b542c4680ef7bfc79',
    messagingSenderId: '606862688252',
    projectId: 'ourobre-project',
    storageBucket: 'ourobre-project.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQnrOugDRlh71XjYgrjChthfjCDYZ0M2o',
    appId: '1:606862688252:web:70d772c0bb4e803a7bfc79',
    messagingSenderId: '606862688252',
    projectId: 'ourobre-project',
    authDomain: 'ourobre-project.firebaseapp.com',
    storageBucket: 'ourobre-project.firebasestorage.app',
  );

}